---
- name: Setup Apache Web Server and Deploy Website
  hosts: webservers
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache (RedHat)
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Apache
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes

    - name: Copy Website Content
      copy:
        src: site-content/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

